### ISSUE TITLE
bug: Adw is not available

### ISSUE THREAD

**Issue by s4dic** [vikdevelop/SaveDesktop#265]
### Linux distribution

Debian 12

### Desktop Environment

Xfce

### Version of the SaveDesktop app

the last I think

### Package type

Native from this repository

### Bug description

Hello, I got theres error :

```
.local/bin/savedesktop
mkdir: cannot create directory ‘/home/home/.cache/io.github.vikdevelop.SaveDesktop’: File exists
mkdir: cannot create directory ‘/home/home/.local/share/io.github.vikdevelop.SaveDesktop’: File exists
Traceback (most recent call last):
  File "/home/home/.local/share/savedesktop/src/main_window.py", line 17, in <module>
    gi.require_version('Adw', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available```

**Comment by vikdevelop** [comment]
Hello,
this means, you don't have installed LibAdwaita library installed on your system. You can try to install it with this command:
```
sudo apt install libadwaita-1
```
You can also try to use the Flatpak or Snap version.

**Comment by s4dic** [comment]
```
apt install libadwaita-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libadwaita-1
```

**Comment by vikdevelop** [comment]
As I wrote above, you can use the Flatpak or Snap version, in which the LibAdwaita library is available.
